[supabase]

API_URL  = "https://fwkpdwxvlrkdscfazelk.supabase.co"
API_KEY  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3a3Bkd3h2bHJrZHNjZmF6ZWxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjExMzY2OTUsImV4cCI6MjAzNjcxMjY5NX0.vZF8P1zilmmp_PrfC4EAp7he4U-_8tELroEypJ3T8V8"